#include QMK_KEYBOARD_H

enum layers {
    _BASE,
    _SYM,
    _MOVE,
    _COLEMAK_DH
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * | PSCR |  1   |  2   |  3   |  4   |  5   |                    |  6   |  7   |  8   |  9   |  0   |RGUI(R|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |TO(3) |  Q   |  W   |  E   |  R   |  T   |                    |  Y   |  U   |  I   |  O   |  P   | BSPC |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |RCTL_T|  A   |  S   |  D   |  F   |  G   |,------.    ,------.|  H   |  J   |  K   |  L   | SCLN |LSFT(K|
 * |------+------+------+------+------+------||TRANSP|    | MUTE ||------+------+------+------+------+------|
 * |MO(2) |  Z   |  X   |  C   |  V   |  B   |`------'    `------'|  N   |  M   | COMM | DOT  | SLSH |MO(2) |
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               | LALT |MO(1) |LGUI_T|/LSFT_T/ TAB  /    \ ENT  \LCTL_T\|RGUI_T|MO(1) | RALT |
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 */
[_BASE] = LAYOUT(
    KC_PSCR, KC_1, KC_2, KC_3, KC_4, KC_5,                                      KC_6, KC_7, KC_8, KC_9, KC_0, RGUI(RSFT(KC_C)),
    TO(3), KC_Q, KC_W, KC_E, KC_R, KC_T,                               KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
    RCTL_T(KC_DQUO), KC_A, KC_S, KC_D, KC_F, KC_G,                              KC_H, KC_J, KC_K, KC_L, KC_SCLN, LSFT(KC_QUOT),
    MO(2), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_TRANSPARENT,                KC_MUTE,KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, MO(2),
           KC_LALT, MO(1), LGUI_T(KC_ESC), LSFT_T(KC_SPC), KC_TAB,      KC_ENT, LCTL_T(KC_BSPC), RGUI_T(KC_ESC), MO(1), KC_RALT),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |TRANSP|  F1  |  F2  |  F3  |  F4  |  F5  |                    |  F6  |  F7  |  F8  |  F9  | F10  | F11  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | MPLY | EXLM |  AT  | HASH | DLR  | PERC |                    | CIRC | AMPR | ASTR | PLUS | PIPE | F12  |
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * | TILD | UNDS |TRANSP| LPRN | RPRN | LCBR |,------.    ,------.| COLN | EQL  | DOT  | MINS |TRANSP| GRV  |
 * |------+------+------+------+------+------||TRANSP|    |TRANSP||------+------+------+------+------+------|
 * |TRANSP|TRANSP|TRANSP| LBRC | RBRC | RCBR |`------'    `------'|TRANSP|TRANSP|  LT  |  GT  | BSLS |TRANSP|
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               |TRANSP|TRANSP|TRANSP|/ TAB  /TRANSP/    \TRANSP\ ENT  \|TRANSP|TRANSP|TRANSP|
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */

[_SYM] = LAYOUT(
    KC_TRANSPARENT, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
    KC_MPLY, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_PLUS, KC_PIPE, KC_F12,
    KC_TILD, KC_UNDS, KC_TRANSPARENT, KC_LPRN, KC_RPRN, KC_LCBR, KC_COLN, KC_EQL, KC_DOT, KC_MINS, KC_TRANSPARENT,
    KC_GRV, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_LBRC, KC_RBRC, KC_RCBR, KC_TRANSPARENT, KC_TRANSPARENT,
    KC_TRANSPARENT, KC_TRANSPARENT, KC_LT, KC_GT, KC_BSLS, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TAB, KC_TRANSPARENT, KC_TRANSPARENT, KC_ENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT),

/* ,-----------------------------------------.                    ,-----------------------------------------.
 * |TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|                    |TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|                    |LCTL(L|LCTL(L|LCTL(L|LCTL(L|TRANSP|TRANSP|
 * |------+------+------+------+------+------|                    |------+------+------+------+------+------|
 * |TRANSP| HOME | PGDN | PGUP | END  |TRANSP|,------.    ,------.| LEFT | DOWN |  UP  | RGHT |TRANSP|TRANSP|
 * |------+------+------+------+------+------||TRANSP|    |TRANSP||------+------+------+------+------+------|
 * |TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|`------'    `------'|TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|TRANSP|
 * `-------------+------+------+------+-.------------.    ,------------.-+------+------+------+-------------'
 *               |TRANSP|TRANSP|TRANSP|/TRANSP/TRANSP/    \TRANSP\TRANSP\|TRANSP|TRANSP|TRANSP|
 *               |      |      |      /      /      /      \      \      \      |      |      |
 *               `---------------------------------'        `---------------------------------'
 *                                                                                   generated by [keymapviz] */


	[_MOVE] = LAYOUT(KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, LCTL(LSFT(KC_LEFT)), LCTL(LSFT(KC_DOWN)), LCTL(LSFT(KC_UP)), LCTL(LSFT(KC_RGHT)), KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_TRANSPARENT, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT, KC_TRANSPARENT),

[_COLEMAK_DH] = LAYOUT(
    KC_PSCR, KC_1, KC_2, KC_3, KC_4, KC_5,                                      KC_6, KC_7, KC_8, KC_9, KC_0, RGUI(RSFT(KC_C)),
    TO(0), KC_Q, KC_W, KC_F, KC_P, KC_B,                                        KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_BSPC,
    RCTL_T(KC_DQUO), KC_A, KC_R, KC_S, KC_T, KC_G,                              KC_M, KC_N, KC_E, KC_I, KC_O, LSFT(KC_QUOT),
    MO(2), KC_Z, KC_X, KC_C, KC_D, KC_V, KC_TRANSPARENT,                KC_MUTE,KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, MO(2),
           KC_LALT, MO(1), LGUI_T(KC_ESC), LSFT_T(KC_SPC), KC_TAB,      KC_ENT, LCTL_T(KC_BSPC), RGUI_T(KC_ESC), MO(1), KC_RALT)

};

bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 1) {
        if (clockwise) {
            tap_code(KC_VOLD);
        } else {
            tap_code(KC_VOLU);
        }
    } else if (index == 0) {
        if (clockwise) {
            tap_code(KC_PGDOWN);
        } else {
            tap_code(KC_PGUP);
        }
    }
    return true;
}


